apiVersion: v1
kind: Secret
metadata:
  name: couchdb-creds
  labels:
    project: valuphone
    environment: production
type: Opaque
data:
  couchdb.user: YW1hemluZy1ib290aA==
  couchdb.pass: YjdkZjI0OTQ1NWE5NDBjNDI5OGI4MjViZjE3OWI3Y2EwYjcyZmUwODZjYzRkY2Q3M2MwYjA1OTE3N2ZlYTRmMA==
