apiVersion: v1
kind: Secret
metadata:
  name: crossbar-creds
  labels:
    project: valuphone
    environment: production
type: Opaque
data:
  crossbar.master-account.name: dmFsdXBob25l
  crossbar.master-account.realm: bm8tcmVhbG0uc2lwLnNpcC1saQ==
  crossbar.master-account.user: a2F6b29hZG1pbg==
  crossbar.master-account.pass: azR6MDB0ZXN0
