apiVersion: v1
kind: Secret
metadata:
  name: freeswitch-creds
  labels:
    project: valuphone
    environment: production
type: Opaque
data:
  freeswitch.event-socket.password: ZWE4ZGU2ODNjNTE5YjI3YWI3M2U5NDQ1NTExYmE1NGQ=
