apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-creds
  labels:
    project: valuphone
    environment: production
type: Opaque
data:
  rabbitmq.user: bm9zdGFsZ2ljLWxpc2tvdg==
  rabbitmq.pass: ODBmZTg1ZDQxMTMxMDk4YjNiMDA1MmJjNTg4MWJiNGFkYTBlODY3YmFjYzgyNWNi
