apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-ingress-controller
  namespace: kube-system
data:
  hsts: 'false'
  hsts-include-subdomains: 'false'
  # options: debug info notice warn error crit alert emerg
  error-log-level: error
  upstream-fail-timeout: '1200'
  # proxy-body-size: '0'
  # proxy-send-timeout: '1200'
  # proxy-read-timeout: '1200'
  # proxy-connect-timeout: '1200'
  # keep-alive: '1200'
  use-gzip: 'true'
  worker-processes: '8'
  ssl-protocols: TLSv1 TLSv1.1 TLSv1.2
  ssl-session-cache: 'true'
  ssl-session-cache-size: 10m
  enable-sticky-sessions: 'true'
