kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: echoserver
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: echoserver
    spec:
      containers:
      - name: echoserver
        image: gcr.io/google_containers/echoserver:1.4
        ports:
        - name: http
          containerPort: 8080
