apiVersion: v1
kind: Pod
metadata:
  name: etcd
  namespace: kube-system
  labels:
    tier: control-plane
    component: state-database
  annotations:
    scheduler.alpha.kubernetes.io/critical-pod: ''
spec:
  hostNetwork: true
  containers:
  - name: etcd-container
    image: gcr.io/google_containers/etcd:3.0.17
    imagePullPolicy: IfNotPresent
    command:
    - /bin/sh
    - -c
    - /usr/local/bin/etcd
    env:
    - name: ETCD_NAME
      value: pluto
    - name: ETCD_ADVERTISE_CLIENT_URLS
      value: https://10.31.4.132:2379
    - name: ETCD_INITIAL_CLUSTER_TOKEN
      value: 2ee9705598dc06df3ab66bbea3a3d440
    - name: ETCD_INITIAL_CLUSTER_STATE
      value: new
    - name: ETCD_INITIAL_ADVERTISE_PEER_URLS
      value: https://10.31.4.132:2380
    - name: ETCD_INITIAL_CLUSTER
      value: saturn=https://10.31.4.134:2380,jupiter=https://10.31.4.131:2380,pluto=https://10.31.4.132:2380
    - name: ETCD_LISTEN_PEER_URLS
      value: https://10.31.4.132:2380
    - name: ETCD_LISTEN_CLIENT_URLS
      value: https://0.0.0.0:2379,http://localhost:4001
    - name: ETCD_DATA_DIR
      value: /var/lib/etcd/default.etcd
    - name: ETCD_CERT_FILE
      value: /etc/ssl/etcd/etcd.pem
    - name: ETCD_KEY_FILE
      value: /etc/ssl/etcd/etcd-key.pem
    - name: ETCD_TRUSTED_CA_FILE
      value: /etc/ssl/etcd/ca.pem
    - name: ETCD_CLIENT_CERT_AUTH
      value: 'true'
    - name: ETCD_PEER_CERT_FILE
      value: /etc/ssl/etcd/etcd.pem
    - name: ETCD_PEER_KEY_FILE
      value: /etc/ssl/etcd/etcd-key.pem
    - name: ETCD_PEER_TRUSTED_CA_FILE
      value: /etc/ssl/etcd/ca.pem
    - name: ETCD_PEER_CLIENT_CERT_AUTH
      value: 'true'
    - name: ETCD_LOG_PACKAGE_LEVELS
      value: etcdserver=WARNING,security=WARNING
    - name: ETCDCTL_ENDPOINT
      value: https://localhost:2379
    - name: ETCDCTL_CERT_FILE
      value: /etc/ssl/etcd/etcd.pem
    - name: ETCDCTL_KEY_FILE
      value: /etc/ssl/etcd/etcd-key.pem
    - name: ETCDCTL_CA_FILE
      value: /etc/ssl/etcd/ca.pem
    - name: ETCDCTL_API
      value: '3'
    - name: ETCDCTL_ENDPOINTS
      value: https://localhost:2379
    - name: ETCDCTL_CACERT
      value: /etc/ssl/etcd/ca.pem
    - name: ETCDCTL_CERT
      value: /etc/ssl/etcd/etcd.pem
    - name: ETCDCTL_KEY
      value: /etc/ssl/etcd/etcd-key.pem
    ports:
    - name: client
      containerPort: 2379
    - name: peer
      containerPort: 2380
    resources:
      requests:
        cpu: 500m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 256Mi
    readinessProbe:
      httpGet:
        host: 127.0.0.1
        port: 2379
        path: /health
      initialDelaySeconds: 45
      timeoutSeconds: 15
    volumeMounts:
    - name: etcd-data
      mountPath: /var/lib/etcd
    - name: etcd-ssl
      mountPath: /etc/ssl/etcd
  volumes:
  - name: etcd-data
    hostPath:
      path: /var/lib/etcd
  - name: etcd-ssl
    hostPath:
      path: /etc/ssl/etcd
