apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: calico-policy-controller
  namespace: calico-system
  labels:
    k8s-app: calico-policy
    kubernetes.io/cluster-service: 'true'
spec:
  replicas: 1
  template:
    metadata:
      name: calico-policy-controller
      namespace: calico-system
      labels:
        k8s-app: calico-policy
        kubernetes.io/cluster-service: 'true'
    spec:
      hostNetwork: true
      containers:
      - name: calico-policy-controller
        image: calico/kube-policy-controller:v0.5.0
        env:
        - name: ETCD_ENDPOINTS
          value: https://saturn.valuphone.local:2379,https://jupiter.valuphone.local:2379,https://pluto.valuphone.local:2379
        - name: ETCD_CA_CERT_FILE
          value: /etc/ssl/etcd/ca.pem
        - name: ETCD_CERT_FILE
          value: /etc/ssl/etcd/etcd.pem
        - name: ETCD_KEY_FILE
          value: /etc/ssl/etcd/etcd-key.pem
        - name: CONFIGURE_ETC_HOSTS
          value: 'true'
        volumeMounts:
        - name: ssl-certs-host
          mountPath: /etc/ssl/certs
          readOnly: true
        - name: ssl-certs-etcd
          mountPath: /etc/ssl/etcd
          readOnly: true
      volumes:
      - name: ssl-certs-host
        hostPath:
          path: /etc/ssl/certs
      - name: ssl-certs-etcd
        hostPath:
          path: /etc/ssl/etcd