apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: wss.valuphone.com
  annotations:
    kubernetes.io/tls-acme: 'true'
    kubernetes.io/ingress.class: 'nginx'
spec:
  tls:
  - hosts:
    - wss.valuphone.com
    secretName: wss-valuphone-com-tls
  rules:
  - host: wss.valuphone.com
    http:
      paths:
      - path: /
        backend:
          serviceName: kazoo
          servicePort: 5555
